baseURL: "https://www.fastro.dev"
languageCode: "en-us"
title: Fastro
paginate: 5
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: UA-165990288-1

minify:
    disableXML: true
    minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archives
                  url: archives
                  weight: 5
                - name: Series
                  url: series/
                  weight: 6
                - name: Tags
                  url: tags/
                  weight: 7
                - name: Search
                  url: search/
                  weight: 8

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Fastro is an independent learning platform for exploring backend, frontend and software automation topics."
    author: Admin
    # author: ["Me", "You"] # multiple authors

    defaultTheme: light
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    # ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    TocOpen: true
    comments: true
    images: ["seo.png"]

    homeInfoParams:
        Title: "Independent learning platform"
        Content: > 
            *Catatan sumber terbuka tentang backend, frontend, dan otomatisasi perangkat lunak.*

    socialIcons:
        - name: github
          url: https://github.com/fastrodev
        - name: twitter
          url: https://twitter.com/fastrodev
        - name: youtube
          url: https://www.youtube.com/channel/UCOx6BLqBZxEO51UuWJEeyhw
        - name: linkedin
          url: https://www.linkedin.com/company/fastro
        - name: email
          url: mailto:hello@fastro.dev
        - name: rss
          url: "index.xml"

    editPost:
        URL: "https://github.com/fastrodev/fastrodev.github.io/blob/main/content"
        Text: "Update" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Fastro"
    #     icon: ""
    #     iconHeight: 28

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series
    author: authors

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        # lineNos: true
        # noClasses: false
        style: vscode

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
